CREATE DATABASE IF NOT EXISTS metabase CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'metabase'@'%' IDENTIFIED BY 'metabase';
GRANT ALL PRIVILEGES ON metabase.* TO 'metabase'@'%';
FLUSH PRIVILEGES;
