server:
  port: 8080

spring:
  application:
    name: gridgain-payments-demo

demo:
  gridgain:
    instance-name: payments-demo-client
    discovery-addresses:
      - gg8-node1:47500
      - gg8-node2:47501
      - gg8-node3:47502
  seed:
    enabled: true
    accounts: 100000
    merchants: 5
    merchant-service-url-pattern: http://merchant-%05d:8080/api/merchant/payments
  oracle:
    jdbc-url: jdbc:oracle:thin:@//oracle-db:1521/FREEPDB1
    username: PAYMENTS_APP
    password: payments_app
    archive:
      poll-interval-ms: 1000
      captured-retention-ms: 15000
    cdc:
      kafka-bootstrap-servers: kafka:9092
      sink-group-id: payments-oracle-cache-sink
      topic-prefix: paymentsdemo
      schema-name: PAYMENTS_APP
      connector-name: paymentsdemo-oracle-reference
      accounts-topic: ACCOUNTS
      merchants-topic: MERCHANTS
  simulator:
    default-rate-per-second: 120
    target-decline-rate: 0.02
  initiator:
    base-url: http://payments-demo-initiator:8080
  fraud:
    threshold: 84.0
  processor:
    base-url: http://payments-demo-app:8080
    callback-url: http://payments-demo-app:8080/api/merchant-results
    merchant-timeout-ms: 10000
