kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: payments-demo
nodes:
  - role: control-plane
    extraPortMappings:
      # Dashboard NodePort -> host:8088
      - containerPort: 30080
        hostPort: 8088
        protocol: TCP
