apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payments-demo

resources:
  - prometheus.yaml
  - grafana.yaml
  - mysqld-exporter.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=prometheus.yml
  - name: grafana-datasource
    files:
      - datasource.yml=grafana/datasource.yml
  - name: grafana-dashboards-provider
    files:
      - dashboards.yml=grafana/dashboards-provider.yml
  - name: grafana-dashboards
    files:
      - grafana/dashboards/payments-flow.json
      - grafana/dashboards/mariadb.json
      - grafana/dashboards/gridgain.json
      - grafana/dashboards/debezium-cdc.json

generatorOptions:
  disableNameSuffixHash: true
